# 网站基本信息
title: 孙林林 - 微分几何
description: 欢迎访问孙林林的个人主页
theme: minima

# 导航栏配置
navbar:
  - name: 简历
    url: /#简历
  - name: 论文
    url: /#论文
  - name: 项目
    url: /#项目
  - name: 其他
    url: /#其他

# 页脚配置
footer:
  copyright: "© 2025 孙林林"
  address: "湖南省湘潭市"
  postal_code: "411105"
  contact: 
    orcid: '<a href="https://orcid.org/0000-0002-8842-2296">ORCID</a>'
    mathscinet: '<a href="https://mathscinet.ams.org/mathscinet/2006/mathscinet/search/author.html?mrauthid=1047065">MathSciNet</a>'
    arxiv: '<a href="https://arxiv.org/a/sun_l_3.html">arXiv</a>'
